### ISSUE TITLE
SynxtaxError: Unexpected token

### ISSUE THREAD

**Issue by arantebw** [chalk/supports-color#103]
I am trying to deploy my Node.js app in Heroku. The build process was successful but upon checking the app, it crashed. I kept on encountering this error pointing to **supports-color** package.

![image](https://user-images.githubusercontent.com/8081121/65104528-45f63b00-da04-11e9-89b3-7eacac0fd103.png)

**Comment by Qix-** [comment]
Yep, you're on an old version of node. That's valid syntax. Please update Node.

**Comment by arantebw** [comment]
@Qix- thank you!
