### ISSUE TITLE
What is wrong with the native `writeStream.getColorDepth`?

### ISSUE THREAD

**Issue by avisek** [chalk/supports-color#108]
Check out:
https://nodejs.org/api/tty.html#tty_writestream_getcolordepth_env

**Comment by Qix-** [comment]
It didn't exist until recently and IIRC I've had some concerns with it.

**Comment by sindresorhus** [comment]
It was also adapted from this package.

We don’t plan to use it as the benefit of this package is that the logic is stable across Node.js versions.

**Comment by jaydenseric** [comment]
I just discovered one limitation… `process.stdout.hasColors` (or `process.stdout.getColorDepth`) is not always defined. For example, a spawned child process that is not a TTY will not have those methods on `process.stdout` or `process.stderr`.
