### ISSUE TITLE
How to force using colors from browser?

### ISSUE THREAD

**Issue by jcubic** [chalk/supports-color#109]
I want to use library that use chalk but in browser, to test my library that process ANSI escape codes. Is there a way other then environment variable so I can set it up and force ansi codes in browser?

I've tried this:
```javascript
process.env.FORCE_COLOR = 3;
window.gradient = require('gradient-string');
```

but after build the file using browserify I don't have colors.

**Comment by Qix-** [comment]
Chalk isn't meant to be used in the browser, nor is this package. It's explicitly intended for use with the standard I/O streams
