### ISSUE TITLE
Change to ESM causes backwards compatibility issues

### ISSUE THREAD

**Issue by yinzara** [chalk/supports-color#116]
The `cordova-webpack-plugin` depends on `supports-color`.  All versions 8.1.1 and earlier work fine with the plugin however when upgrading to `supports-color` 9.0.0 I get the following error:
```
require() of /pathto/mycordovaproject/node_modules/supports-color/index.js from /pathto/mycordovaproject/plugins/cordova-plugin-webpack/dist/options/webpack.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /pathto/mycordovaproject/node_modules/supports-color/package.json.
```

**Comment by yinzara** [comment]
I think the issue is that supports-color now ONLY supports ESM syntax (it doesn't provide a hybrid configuration to allow for both).   I think this is probably going to cause a lot of problems with a lot of people upgrading to this version.

It might be a better solution to add a babel compilation step to create a CJS version of the library and then configure that appropriately in the package.json so that either ESM or CJS imports function correctly.

https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html  -  this gives some information about using TypeScript as the transpiler but you could replace it with Babel in CJS configuration as well so you don't have to convert the project to typescript.

**Comment by mirsella** [comment]
hello, follow up to this warning, its now a error in node

node v23.1.0
```
 ERROR  (node:31318) ExperimentalWarning: CommonJS module /home/mirsella/dev/hypertube/node_modules/.pnpm/debug@4.3.7_supports-color@9.4.0/node_modules/debug/src/node.js is loading ES Module /home/mirsella/dev/hypertube/node_modules/.pnpm/supports-color@9.4.0/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
```

**Comment by Qix-** [comment]
That has nothing to do with `chalk`, that's a known `debug` issue. Please see https://github.com/debug-js/debug/issues/975.
