### ISSUE TITLE
Implement `NO_COLOR` informal specification

### ISSUE THREAD

**Issue by mondeja** [chalk/supports-color#129]
See https://no-color.org/

> Command-line software which adds ANSI color to its output by default should check for the presence of a `NO_COLOR` environment variable that, when present (regardless of its value), prevents the addition of ANSI color.

This is implemented by some other color terminal libraries like [go-supportscolor](https://github.com/jwalton/go-supportscolor).

**Comment by Qix-** [comment]
Please search next time. https://github.com/chalk/supports-color/issues/105#issuecomment-542271445
