### ISSUE TITLE
`navigator.userAgentData`

### ISSUE THREAD

**Issue by Richienb** [chalk/supports-color#133]
More reliable way of checking the browser:

```js
const isBlinkBasedBrowser = Boolean(navigator.userAgentData.brands.find(({brand}) => brand === 'Chromium'));
```

vs

https://github.com/chalk/supports-color/blob/4f459ee311817cfad1332731a2c1060e07b2015e/browser.js#L3

**Comment by sindresorhus** [comment]
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData#browser_compatibility). - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

So we still need to keep the old check as fallback.
