### ISSUE TITLE
Support importing via deno

### ISSUE THREAD

**Issue by binyamin** [chalk/supports-color#136]
### Problem
Currently, Deno imports default to `browser.js`, because Deno imports use URLs like a browser. `browser.js` reports "no color" because Deno's user-agent doesn't look like Chromium. Deno is a runtime like Node.js, so `index.js` is ideal. Using a Deno-friendly CDN, such as esm.sh, `index.js` would transpile fine.

### Solution
Add "deno" to the `exports` map in the `package.json`.
```json
{
  "exports": {
 	"node": "./index.js", 
        "deno": "./index.js",
 	"default": "./browser.js"
  }
}
```

**Comment by sindresorhus** [comment]
I'm not really interested in adding special Deno support. Deno is soon going to have close to full Node.js support: https://deno.com/blog/changes#compatibility-with-node-and-npm

**Comment by binyamin** [comment]
@sindresorhus How about changing "default" to "browser"? That's more accurate, and doesn't restrict other runtimes to the browser version.
