### ISSUE TITLE
GitHub Action support truecolor

### ISSUE THREAD

**Issue by idanran** [chalk/supports-color#143]
test: https://github.com/idanran/test-ci/actions/runs/3613736936/jobs/6089687699
![image](https://user-images.githubusercontent.com/96647698/205497070-69a6b98f-a02d-4800-934f-2dc1fe9b3bf3.png)

test code: https://github.com/idanran/test-ci/blob/main/test.mjs

**Comment by Qix-** [comment]
PR welcome :)
