### ISSUE TITLE
Color Detection not working on ubuntu

### ISSUE THREAD

**Issue by Fantus** [chalk/supports-color#21]
Hi,

i tried using the new 1.3.0 version but the color detection is not working correctly. Iam using ubuntu 14.10

For me

	if ('UPSTART_JOB' in process.env) {
		return false;
	}

is always true.

however i tested **('UPSTART_JOB' in process.env)  ? true : false;** on different systems

system | node | result
----------| --------| -----
ubuntu 14.10| v0.10.32 | true
ubuntu 14.10| v0.12.0| true
debian 6.0.10 | v0.10.33 | false
debian 7.7|v0.12.0| false

so for debian it works correctly.

i switched back to version 1.2.1 for now as it works for me.

**Comment by jbnicolai** [comment]
Thank you for the report! I'll look into it myself later today - I must have an Ubuntu image lying around somewhere.

**Comment by Fantus** [comment]
small addition:
on ubuntu:
`process.env.UPSTART_JOB`
**unity7**

debian:
`process.env.UPSTART_JOB`
**undefined**

**Comment by kevva** [comment]
Anyone have an idea if `UPSTART_JOB` is set on older Ubuntu distros?

**Comment by sindresorhus** [comment]
I've removed it for now and done a new release. We can add it back if/when we sort this out.

**Comment by jbnicolai** [comment]
@sindresorhus good call. Was just about to do the same. The /UPSTART_JOB/ check was premature, and doesn't do the right thing.

**Comment by sindresorhus** [comment]
@Qix- Any thoughts on this?

**Comment by Qix-** [comment]
@sindresorhus is this for a specific terminal on Ubuntu, i.e. Unity's basic terminal? Or the default TTY that comes with the server?

I'm booting up my ubuntu box now, though I think it's server. I'll have to snag the latest desktop image.

**Comment by jbnicolai** [comment]
To be honest, I feel like we can close this issue after @sindresorhus' revert of what introduced the issue

> I've removed it for now and done a new release. We can add it back if/when we sort this out.

This originally comes from #14, but I no longer think this is an actual issue. If the environment is reporting as an interactive TTY supporting colors, we should assume it supports colors. If upstart does not set this correctly, I feel the issue lies with upstart

@sindresorhus @Qix- feel free to reopen, but I think we can let this rest.
