### ISSUE TITLE
Use terminfo database for systems providing the `TERM` environment variable

### ISSUE THREAD

**Issue by Qix-** [chalk/supports-color#29]
`TERM` has an endless list of possible values:

<img width="635" alt="screen shot 2015-07-26 at 1 08 14 pm" src="https://cloud.githubusercontent.com/assets/885648/8895436/6b07a482-3397-11e5-98ef-e1db350b0434.png">

The _correct_ way would be to look up the terminal information given the `TERM` environment variable and see what capabilities the terminal has. This includes what kind of underline/overline it has, whether or not the terminal supports color at all, how many colors it supports, and (if I read the man page correctly) even the escape character that should be used.

I understand a lot of that information isn't pertinent to `supports-color` specifically, but the color support bits do.

Currently, we're just testing for a few of the common `TERM` values via regex.

**Comment by sindresorhus** [comment]
I've considered it in the past, but I went with the simple and practical way instead. What's the benfit of doing this? What kind of color support does it return? Do you have an example? I really don't want to spawn to get this information, is there a way to get what we need by embedding the relevant parts of the `terminfo` DB or something?

**Comment by Qix-** [comment]
The `terminfo` database is per-machine, and it's pretty big.

```bash
find /usr/share/terminfo -type f | xargs cat | wc -c
```

The benefit is that, no matter what terminal the user is using (less windows terminals), it will be able to accurately detect color support.

> max_colors       colors     Co       maximum number of colors on screen
> max_pairs         pairs       pa       maximum number of color-pairs on the screen
> no_color_video ncv         NC      video attributes that cannot be used with colors

For instance, here is the output for `xterm-256color`:
```
$ infocmp
#	Reconstructed via infocmp from file: /usr/share/terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smm=\E[?1034h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
```

Notice `colors#256`.

And for `linux`:
```
infocmp linux
#	Reconstructed via infocmp from file: /usr/share/terminfo/6c/linux
linux|linux console,
	am, bce, ccc, eo, mir, msgr, xenl, xon,
	colors#8, it#8, ncv#18, pairs#64,

        . . .
```

Only `colors#8` colors (16-bit palette).

And for `rcons`:
```
$ infocmp rcons
#	Reconstructed via infocmp from file: /usr/share/terminfo/72/rcons
rcons|BSD rasterconsole,
	am, km, msgr,
	cols#80, lines#34,

        . . .
```

Missing `colors` attribute, meaning no colors.

**Comment by sindresorhus** [comment]
I'm open to having it as a last resort if we can find a way to efficiently get the information. Maybe by reading the correct file `/usr/share/terminfo/78/$TERM` syncronously and parsing out what we're looking for?

**Comment by Qix-** [comment]
That's exactly what I'm thinking, though I'm still looking into exactly how the `/78/` is determined.

**Comment by Qix-** [comment]
@sindresorhus I wrote https://www.npmjs.com/package/terminfo a while back - it's fast and pretty minimal (it's got a long list of stuff but it's efficient and has no dependencies).

It'd be nice to require it as-needed at the end of the function and have it replace all of the screen/xterm regex nonsense, plus have it support any terminal registered in the terminfo database.

Even after these years, I just don't see a reason not to do it.

**Comment by sindresorhus** [comment]
https://github.com/chalk/supports-color/pull/50#issuecomment-312237430
