### ISSUE TITLE
Detect `screen-256color`?

### ISSUE THREAD

**Issue by sindresorhus** [chalk/supports-color#33]
Should we detect `screen-256color` and return level 2 color support?

http://superuser.com/questions/424086/what-is-the-difference-between-screen-256-color-and-xterm-256color

Found it here: https://github.com/junegunn/fzf#rendering-issues

// @Qix-

**Comment by Qix-** [comment]
We can. It's for GNU `screen`.

**Comment by Qix-** [comment]
Released as `3.2.2`.
