### ISSUE TITLE
Color disabled on Travis-CI?

### ISSUE THREAD

**Issue by isaacs** [chalk/supports-color#41]
It looks like `env.CI` will suppress color, which is probably the right choice for _most_ CI servers, but travis-ci should perhaps get a pass, since it handles terminal colors quite nicely.

Would you be open to allowing color if `env.TRAVIS` is set?

**Comment by Qix-** [comment]
@sindresorhus this is what I was talking about :P

**Comment by dunkelstern** [comment]
So a "disable color" environment variable would be useful. If i run the stuff in a pseudo terminal from an IDE that does not understand color i get Escape sequences too.

**Comment by Qix-** [comment]
@dunkelstern We have #34 and #31 currently open right now for solving this - could use more discussion on them as there seems to be a rift :) Feel free to voice your thoughts!

**Comment by Qix-** [comment]
@isaacs Going to go ahead and do this since it was determined TeamCity should get a pass too.

My hope is, in the future, there is a more unified way of determining such things - I really think we should be looking at the terminfo database but @sindresorhus seems pretty against it.

**Comment by Qix-** [comment]
Released as `3.2.3`. Let me know if that doesn't work.
