### ISSUE TITLE
Support PuTTY as a terminal type

### ISSUE THREAD

**Issue by BitLooter** [chalk/supports-color#44]
By default PuTTY reports its terminal type as 'putty'. supports-color doesn't recognize this, so it reports a PuTTY terminal as not supporting color. PuTTY does support color, though - you can set the terminal-type string can be set to 'xterm-256' in PuTTY's options and colors work fine.

**Comment by Qix-** [comment]
You should do that anyway, to be honest. Putty has changed the way it supports colors over the years and I assume it has used `putty` as a `TERM` value for a while. A lot of programs check the terminfo database and `xterm-256color` is going to be the most up to date and probably give you the best stability.
