### ISSUE TITLE
Show colors in TeamCity 9.1+

### ISSUE THREAD

**Issue by anton-rudeshko** [chalk/supports-color#46]
See https://blog.jetbrains.com/teamcity/2015/07/teamcity-9-1-release-truly-historical-and-very-personal-builds/

**Comment by sindresorhus** [comment]
PR welcome

**Comment by anton-rudeshko** [comment]
As always :)

**Comment by Qix-** [comment]
Any chance you could see what level of ANSI support they have starting 9.1? Is it 16 colors, 256 colors or full RGB (truecolor) support?

**Comment by Qix-** [comment]
Released in `3.2.1`.
