### ISSUE TITLE
undefined is not an object when used in a React Native project. 

### ISSUE THREAD

**Issue by tetreault** [chalk/supports-color#47]
Hello, 

I'm messing around with React Native and I wanted to try using chalk to help make some of the logs more clear. I'm running into an issue though at the import/require step. 

If I try `import chalk from 'chalk';` or `const chalk = require('chalk');` I receive the following error: 

![screen shot 2016-12-28 at 4 06 12 pm](https://cloud.githubusercontent.com/assets/5934354/21531645/959f2cc2-cd17-11e6-814e-0fc5d82594db.png)

Here are the output of the React Packager: 
```
[12/28/2016, 3:59:04 PM] <START> Requesting bundle bundle_url: /index.ios.bundle?platform=ios&dev=true&minify=false
[12/28/2016, 3:59:04 PM] <END>   Requesting bundle bundle_url: /index.ios.bundle?platform=ios&dev=true&minify=false (25ms)
[12/28/2016, 3:59:04 PM] <START> Symbolicating
[12/28/2016, 3:59:04 PM] <END>   Symbolicating (319ms)
[12/28/2016, 3:59:04 PM] <START> Symbolicating
[12/28/2016, 3:59:05 PM] <END>   Symbolicating (306ms)
```

If I'm following the stack trace correctly its complaining about lines 2-4 in supports-color/index.js: 
```
var argv = process.argv;

var terminator = argv.indexOf('--');
```

Further info: 
**OS**: OSX  v10.11.6
**Node**: v5.9.1
**NPM**: v3.10.8
**React Native**: v0.39.2
**Chalk**: v^1.1.3

**Comment by Qix-** [comment]
I'm not seeing how that stack trace is pointing to `supports-color`. I've not played with react native but does `process.argv` not exist in that environment?

**Comment by tetreault** [comment]
@Qix- when I click on the top <unknown> index.js line 4 it brings me to the index.js for supports-color. To be honest I'm not sure if `process.argv` exists in that environment and guess I'll have to figure that out. I posted this here because I hadn't seen it anywhere, and it is definitely happening at the require/import step when I try to use chalk. I'll try more digging and maybe xposting to SO to see what else I can find out.

**Comment by tetreault** [comment]
Okay fair enough, thank you for your help!

**Comment by Qix-** [comment]
No problem! Sorry I couldn't be of more help.

**Comment by AndrewKvalheim** [comment]
Ran into this when trying to use Chalk with `FORCE_COLOR` while logging in React Native. sindresorhus/has-flag#3 suggests that React Native should provide a `process.argv`.
