### ISSUE TITLE
Fails to detect 256 colors because of COLORTERM

### ISSUE THREAD

**Issue by IonicaBizau** [chalk/supports-color#48]
It enters [here](https://github.com/chalk/supports-color/blob/9170da93dde30a88040b388176628b482bf64515/index.js#L53-L55), before entering [here](https://github.com/chalk/supports-color/blob/9170da93dde30a88040b388176628b482bf64515/index.js#L61-L62).

Which means it ends with 16 color support, instead of 256.

`echo $COLORTERM` outputs `truecolor`.

Reordering the `if`s fixes the issue, but wondering if there's a better solution.

Context: [this](https://twitter.com/robjloranger/status/820663010683297793) and [this](https://twitter.com/changelog/status/820651011295637505).

/cc @Qix- @sindresorhus

**Comment by Qix-** [comment]
Could have sworn I responded to this.

I agree. When we created the module, everything was `return true;` unless nothing indicated color was supported. Then when we introduced levels, ordering became important.

The xterm check should indeed go above the `COLORTERM` check.

**Comment by Qix-** [comment]
I'll let it run through travis and then release it.

**Comment by IonicaBizau** [comment]
@Qix- Thank you very much! :+1:
