### ISSUE TITLE
Don't exclude new versions of Windows

### ISSUE THREAD

**Issue by Qix-** [chalk/supports-color#49]
Right now we have a blanket clause for `win32` to disable colors; this is no longer the case on windows.

@sindresorhus you'll have a better idea as to how to properly detect the correct version of windows. Thoughts?

**Comment by sindresorhus** [comment]
We need to detect the correct minimum `os.release()` and Node.js version. I think it's the Windows Anniversary Update. The [libuv changes](https://github.com/libuv/libuv/commit/445e3a1f06b2a049e2b50b7edf2992ce80167014) (libuv 1.10.2) needed are still not in Node.js master, I think. So this will have to wait.

**Comment by ViceIce** [comment]
libuv 1.10.2 was included in [node 7.5.0](nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#2017-01-31-version-750-current-evanlucas) and 1.11.0 in [node 7.6.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#2017-02-21-version-760-current-italoacasas)
