### ISSUE TITLE
return false when run with less -R

### ISSUE THREAD

**Issue by jcubic** [chalk/supports-color#52]
Don't know if it's possible to handle this case, but I have [syntax highlight script](https://github.com/jcubic/prism-cli) and I'm adding support for terminals that don't suport 256 colors, like ansi term from emacs, and I'm testing this from xterm on GNU/Linux:

```
prism.js -f prism.js -l javascript | less -R
```

and when I've added `console.log(supportsColor);` I've got `false` even that 256 colors work.

**Comment by Qix-** [comment]
Whenever you pipe to another program, `supports-color` is going to detect it as not a TTY (since it isn't).

Prefix your command with `FORCE_COLORS=1`.

```
FORCE_COLORS=1 prism.js -f prism.js -l javascript | less -R
```

**Comment by jcubic** [comment]
Yes, I've just found that in the source code. thanks for quick reply.

**Comment by jcubic** [comment]
Is it possible to force 256 colors?
