### ISSUE TITLE
Force 256 colors

### ISSUE THREAD

**Issue by jcubic** [chalk/supports-color#53]
I believe it's not possible looking at the code, but it would be great if you could force 256 colors like this:

```
FORCE_COLOR=256 prism.js -f prism.js -l javascript | less -R
```

**Comment by sindresorhus** [comment]
From the readme:

> Explicit 256/truecolor mode can be enabled using the --color=256 and --color=16m flags, respectively.

**Comment by jcubic** [comment]
Sorry, I've miss that in readme. thanks.
