### ISSUE TITLE
Check for env.CONTINUOUS_INTEGRATION

### ISSUE THREAD

**Issue by stevenvachon** [chalk/supports-color#54]
instead of just `process.env.CI`.

**Comment by Qix-** [comment]
Why?

**Comment by stevenvachon** [comment]
Because other CI's may not have `CI`. There must be some reason why Travis defines both.

**Comment by Qix-** [comment]
Are there any other CI's that support it?

**Comment by kevva** [comment]
Only one I found was Shippable. Although all of them supports `CI` AFAIK which makes this kinda moot.

**Comment by Qix-** [comment]
Agreed. `CI` should be sufficient.

Thanks for the report :)
