### ISSUE TITLE
has16m is false but terminal supports Truecolor

### ISSUE THREAD

**Issue by bokub** [chalk/supports-color#62]
I found this issue using chalk, but it's color support related so I thought it was a better idea to submit my issue here.

Check out the following code. The same string is colored using the default chalk instance, a chalk forced to level 2, and a chalk forced to level 3.

```javascript
// Default chalk
let chalk = require('chalk');
console.log(chalk.supportsColor);
print(chalk);

// 256 colors chalk
let ch256 = new chalk.constructor({level: 2});
print(ch256);

// Truecolor chalk
let ch16m = new chalk.constructor({level: 3});
print(ch16m);

function print(c) {
    let result = '';
    for(let i =0; i < 60; i++){
        result += c.rgb(255 - 2*i, 0, 2*i)('█');
    }
    console.log('    ' + result);
}
```

The `supportsColor` returns this: `{ level: 2, hasBasic: true, has256: true, has16m: false }
`, so it looks like my terminal does not support Truecolor.

However, the printed colors look like that:
![capture du 2017-07-19 17-22-42](https://user-images.githubusercontent.com/17952318/28375103-e9652a1c-6ca6-11e7-8844-7ab9e70f3e1f.png)

It is clear that my terminal actually supports Truecolor. Why is it not detected ?

What if I always force level 3 in my code ? Can it impact users who only support 256 colors ? 

Thanks a lot
_____

supports-color version: 2.0.0
chalk version: 2.0.1
Ubuntu 16.04.2 LTS
gnome-terminal 3.18.3

**Comment by Qix-** [comment]
Right now, no. Terminals don't expose anything that identifies them having 16m colors, unfortunately.

@sindresorhus we should make more progress on that.

**Comment by sindresorhus** [comment]
We could hard-code it if `gnome-terminal` exposes its name somehow.

@bokub What's the output of running `echo $TERM_PROGRAM`?

**Comment by bokub** [comment]
`$TERM_PROGRAM` is empty, `$TERM` is `xterm-256color`, unfortunately.

However, the command `ps -p$PPID` returns the following:
```bash
  PID TTY          TIME CMD
 3798 ?        00:00:13 gnome-terminal-
```
You could check if the result of the command contains `gnome-terminal`. 

_____

> What if I always force level 3 in my code ? Can it impact uses who only support 256 colors ?

Were you answering this question when you said 'Right now, no' @Qix- ?

**Comment by Qix-** [comment]
> What if I always force level 3 in my code ? Can it impact users who only support 256 colors ?

Yeah don't do that. It'll cause a lot of issues for users that don't have the new codes - the best case is that they won't see _any_ color, worst case is they get output `[38;2;185;2;217mlike this`.

**Comment by sindresorhus** [comment]
> However, the command `ps -p$PPID` returns the following:

We can't spawn a child process. That's too expensive.

**Comment by kevva** [comment]
What does `echo $VTE_VERSION` and `echo $COLORTERM` (this one doesn't work in later versions of `gnome-terminal`) give you?

**Comment by bokub** [comment]
$VTE_VERSION is 4205
$COLORTERM is undefined

**Comment by Qix-** [comment]
@kevva I can't immediately find any docs on `VTE_VERSION` - what is it?

**Comment by kevva** [comment]
It's set by `gnome-terminal` and shows the [`vte`](https://developer.gnome.org/vte/unstable/) version. We can probably use that flag to detect `gnome-terminal`.

**Comment by Qix-** [comment]
Is there a corresponding version we can use to more accurately detect the level of support? Or just the existence of the variable?

**Comment by kevva** [comment]
Just the existence I think. I'm not aware of any other program setting it.

**Comment by sindresorhus** [comment]
@bokub Can you open an issue on the `gnome-terminal` issue tracker asking them to implement `$TERM_PROGRAM` and `$TERM_PROGRAM_VERSION`?

**Comment by Delta456** [comment]
Is this issue fixed now?

**Comment by sindresorhus** [comment]
@Delta456 https://blog.sindresorhus.com/issue-bumping-e3b9740e2a0

**Comment by Delta456** [comment]
I am sorry if I bumped it but I think we can use node-cpp for the system api to detect it.

**Comment by Qix-** [comment]
There's no way we're bringing in a native module to `supports-color`, sorry.

Unless the terminal emulator exposes a way for us to detect the truecolor support (since traditional ways such as terminfo have not evolved to keep up) there's nothing actionable we can do.

We've not heard back in over a year so I'm going to close this since there's nothing (currently) actionable.

**Comment by StoneCypher** [comment]
seems like someone could just put an envvar to let a user declare their own status?
