### ISSUE TITLE
`FORCE_COLOR` should support setting a specific level

### ISSUE THREAD

**Issue by sindresorhus** [chalk/supports-color#78]
For predictability when testing tools that output color.

I'm open to suggestions on the best way to do this.

**Comment by Qix-** [comment]
Well seeing as how most people that use it set it to `1` which is pretty sane, perhaps setting it to `2` or `3` would set the specific levels.

**Comment by bokub** [comment]
I agree with @Qix- , `FORCE_COLOR=2` or `FORCE_COLOR=3` seems the most obvious way to do it. 

I actually thought it was implemented, and had to look at the code to check 🤷

**Comment by plroebuck** [comment]
Anyone consider using `FORCE_COLORLEVEL` rather than turning a boolean value numeric?

**Comment by Qix-** [comment]
@plroebuck No. `FORCE_COLORLEVEL=0` and `FORCE_COLOR=1` has no clear meaning. Introducing another var here doesn't help.

**Comment by plroebuck** [comment]
I was emulating `DEBUG` and `DEBUGLEVEL`.

**Comment by Qix-** [comment]
What's `DEBUGLEVEL`?

**Comment by plroebuck** [comment]
In old school C programming, `DEBUG` was boolean CPP flag to enable your debugging code/output. `DEBUGLEVEL` (accessed with `DEBUG`) was used numerically to determine the level (higher numbers increased the amount of spew).

**Comment by Qix-** [comment]
I don't see that as being relevant, though. That's for logging level and they operate independently. Supports color doesn't return a boolean, it returns a level - 0 being "no color".

Further, I don't see anything mentioning `DEBUGLEVEL` in a quick google search, and have never come across it in my experience as a C programmer.
