### ISSUE TITLE
VSCODE_PID check breaks color suppression in stream redirection in VSCode's integrated terminal

### ISSUE THREAD

**Issue by rbergman** [chalk/supports-color#79]
The check for `VSCODE_PID` to support the VSCode debugger in the following line breaks ansi color code suppression when redirecting `stdout` or `stderr` in the VSCode integrated terminal: https://github.com/chalk/supports-color/blob/master/index.js#L52

For example, the following commands in a normal terminal produces the expected results:

```
$ node -p "process.stdout.isTTY"
true
$ node -p "process.stdout.isTTY" | cat
undefined
$ node -p "require('supports-color').stdout"
{ level: 3, hasBasic: true, has256: true, has16m: true }
$ node -p "require('supports-color').stdout" | cat
false
```

However, in VSCode's integrated terminal, the following output occurs:

```
$ node -p "process.stdout.isTTY"
true
$ node -p "process.stdout.isTTY" | cat
undefined
$ node -p "require('supports-color').stdout"
{ level: 3, hasBasic: true, has256: true, has16m: true }
$ node -p "require('supports-color').stdout" | cat
{ level: 1, hasBasic: true, has256: false, has16m: false }
```

The `VSCODE_PID` check is causing the last line above to report level 1 support, rather than the expected level 0 during a redirection.  A real world case in which this is a problem can be demonstrated by running the following:

Terminal:
```
$ node -p "o=JSON.stringify({foo:'bar'});if(require('chalk').enabled){require('cardinal').highlight(o)}else{o}" | jq
{
  "foo":"bar"
}
```

VSCode:
```
$ node -p "o=JSON.stringify({foo:'bar'});if(require('chalk').enabled){require('cardinal').highlight(o)}else{o}" | jq
parse error: Invalid numeric literal at line 1, column 2
```

**Comment by sindresorhus** [comment]
// @vwuweiweiwu

**Comment by sindresorhus** [comment]
// @wuweiweiwu

**Comment by mysticatea** [comment]
This false positive seems to break [the table formtter tests](https://github.com/eslint/eslint/blob/85a5191b9ae67ade8b6fe8a8849a0922e613c26b/tests/lib/formatters/table.js) of ESLint since that tables are colored wrongly.

**Comment by wuweiweiwu** [comment]
Hm. weird. They must've made updates to the debugger terminal emulator
