### ISSUE TITLE
Failed to minify code from this file

### ISSUE THREAD

**Issue by Eason-Wu** [chalk/supports-color#84]
It occured an error when use it with create-react-app. because of socre code wrote with ES6, can you please release an ES5 libs ?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
