### ISSUE TITLE
TypeError: (env.TERM_PROGRAM_VERSION || "").split is not a function

### ISSUE THREAD

**Issue by mickmak-busicat** [chalk/supports-color#86]
I just upgraded MacOS to Mojave. And my terminal `TERM_PROGRAM_VERSION` became `421`. And the following line seems not working on my machine.
```
    TypeError: (env.TERM_PROGRAM_VERSION || "").split is not a function

      at supportsColor (node_modules/jest-each/node_modules/supports-color/index.js:92:61)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:152:7)
```

**Comment by sindresorhus** [comment]
I don't really see how this is possible. Environment variables are always strings or `undefined`, both of which cases should go to `""` where `.split()` would work. Sounds like something else you're running is setting `TERM_PROGRAM_VERSION` to an actual number.

**Comment by Qix-** [comment]
What @sindresorhus said.

If you want to debug this, use `Object.defineProperty` on the env map to throw an error when it gets set. Then you'll know what is setting it to a number.

**Comment by mickmak-busicat** [comment]
Thanks for the response. I am not sure why my `TERM_PROGRAM_VERSION` became an integer value during run time. I modified that line to ``(`${env.TERM_PROGRAM_VERSION}` || "").split`` to cast it as a string then fixed my problem.

**Comment by Qix-** [comment]
You modified the Node package directly? Don't do that. That's not portable.

Instead, **figure out what's writing it as an integer** because whatever code is doing it is breaking the contract of `process.env` being a `String => String` map.
