### ISSUE TITLE
Colour support on TravisCI

### ISSUE THREAD

**Issue by Berkmann18** [chalk/supports-color#92]
I'm currently working on a package where I'm planning on switching to `chalk` and up to now TravisCI didn't have any problems with colours on the console (using `colors`) but after pushing some code with **passing** tests (on the `chalk`-based codebase), Travis seems to disable colours which make all the tests fail.

I've understood from this [comment](https://github.com/chalk/chalk/issues/234#issuecomment-351849373) that TravisCI seems to non-determistically change `supports-color` but I'm unsure if there's a fix for that or if I have to manually enable it using `chalk.enable = true` or even set the `chalk.level` to something other than `0` (which is what I get on the TravisCI log).

EDIT: `if (!chalk.enabled) chalk.enabled = true;` doesn't help.

**Comment by Berkmann18** [comment]
> Hi there Max,
>
> Thanks for getting in touch with us about this, and I've escalated this as a feature request to our Product team. Unfortunately I can't say when or if this will be implemented.

**Comment by Berkmann18** [comment]
I've emailed them again as I've received no response other than the above.

**Comment by sindresorhus** [comment]
@Berkmann18 Try posting here instead: https://travis-ci.community/

**Comment by sindresorhus** [comment]
Closing as TravisCI is no longer relevant.
