### ISSUE TITLE
The isTTY check prevents showing colors when piping spawn output with child_process

### ISSUE THREAD

**Issue by vjpr** [chalk/supports-color#94]
Say I writing a cli task runner that runs node processes with spawn. If I want to pipe the output to the stdout (so I can intercept the data and process if necessary), tty will not be set. And then you have to do some complicated stuff with drawback like native deps (https://stackoverflow.com/questions/31866207/spawning-a-child-process-with-tty-in-node-js) to emulate a tty (or maybe there is an easier way).

So isTTY doesn't seem like is prevents supporting colors. Or is this the only way to detect `cat file | node app` or something?

**Comment by sindresorhus** [comment]
It’s the only way to detect piping, yes.

**Comment by vjpr** [comment]
So workaround is to pass `FORCE_COLOR=1` (and `DEBUG_COLORS=1` if you use `debug`) into the spawn opts when you are running another node process.
