### ISSUE TITLE
FATAL: Unable to load template: Unexpected token { in index.js

### ISSUE THREAD

**Issue by EberhardtRobert** [chalk/supports-color#95]
We are using supports-color in our npm based buildtask in order to  create jsdoc of our project. Since January 2019 This process does not work anylonge we get the message:

**FATAL: Unable to load template: Unexpected token {**

We found out that the problem is casued by supports-color\index.js. Since version 6.0 you are using 

const{env}  = process in line 5. 

Before  you had

const env  = process

Can you please tell me what to do to use supports-color again ?

We are using the following maven plugin configuration to trigger the js doc generation

<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <executions>
                   <execution>
                        <id>install-node-and-npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <nodeVersion>v5.9.1</nodeVersion>
                            <npmVersion>3.8.5</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm-install</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>gulp-clean</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>gulp</goal>
                        </goals>
                        <configuration>
                            <arguments>clean</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>gulp-build</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>gulp</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

Best Regards Robert Eberhardt

**Comment by Qix-** [comment]
Yes, that's called es6 and object destructuring. You need to figure out how to get your build tools to handle ES6.

Nothing we're doing should be breaking you in this day and age.
